<br />
<br />
<h1 class="center"><?php echo $this->artist->getName()?></h1>
<div id="panel-artist" class="panel">

	<div class="panel-content">
		<img alt=""
			src="<?php echo $this->artist->showImage('extralarge')?>" />
		<h2>Bio</h2>
		<p><?php echo nl2br($this->artist->getBiography())?></p>

	</div>
</div>
<div class="clear"></div>
<div id="panel-artist-top-albums" class="panel">
	<h1 class="center">Top Albums</h1>
	<div class="panel-content">
		<ul class="item-container">
		<?php foreach($this->topAlbums as $album){?>
			<li class="item"><div class="item-index"><?php echo $album->getPosition()?></div>
				<a href="#"><img alt=""
					src="<?php echo $album->showImage('small')?>" /></a>
				<div class="item-desc">
					<a href="#"><?php echo $album->getName()?></a>
					<div class="item-note">Playcount: <?php echo $album->getPlaycount()?></div>

				</div>
			</li>
		<?php }?>
		</ul>
	</div>
</div>

<div id="panel-artist-top-songs" class="panel">
	<h1 class="center">Top Songs</h1>
	<div class="panel-content">
		<ul class="item-container">
		<?php foreach($this->topSongs as $song){?>
			<li class="item"><div class="item-index"><?php echo $song->getPosition()?></div>
				<a href="#"><img alt=""
					src="<?php echo $song->showImage('small')?>" /></a>
				<div class="item-desc">
					<a href="#"><?php echo $song->getName()?></a>
					<div class="item-note">Listeners: <?php echo $song->getListeners()?></div>

				</div>
			</li>
		<?php }?>
		</ul>
	</div>
</div>

<div class="clear"></div>
<br/><br/>