<br />
<br />
<div id="panel-main-top-artists" class="panel">
    <h1 class="center">Top Artists </h1>
    <div class="panel-content">

        <ul class="item-container">
        <?php foreach($this->topArtists as $artist){?>
        <li class="item"><div class="item-index"><?php echo $artist->getPosition()?></div>
            <a href="#"><img alt="" src="<?php echo $artist->hasImageSize('small') ? 
            	$artist->getImage('small') : $this->baseUrl() . Zend_Registry::get('defaultImages')->artist->small?>" /></a>
            <div class="item-desc">
                <a href="<?php echo $this->url(array('controller' => 'artist', 'action' => 'info', 'name' => $artist->getName()))?>"><?php echo $artist->getName()?></a>
                <div class="item-note">Listeners: <?php echo $artist->getListeners()?></div>
            </div>
        </li>
		<?php }?>
    </ul>
    </div>
</div>

<div id="panel-main-top-songs" class="panel">
    <h1 class="center">Top Songs</h1>
    <div class="panel-content">
        <ul class="item-container">
        <?php foreach($this->topSongs as $song){?>
            <li class="item"><div class="item-index"><?php echo $song->getPosition()?></div>
                <a href="#"><img alt=""
                    src="<?php echo $song->hasImageSize('small') ? 
                    	$song->getImage('small') : $this->baseUrl() . Zend_Registry::get('defaultImages')->song->small?>" /></a>
                <div class="item-desc">
                    <a href="#"><?php echo $song->getName()?></a>
                    <div class="item-note">Artist: <?php echo $song->getArtist()->getName()?></div>
                    <div class="item-note">Listeners: <?php echo $artist->getListeners()?></div>

                </div></li>
		<?php }?>
        </ul>
    </div>
</div>

