<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Music </title>
		<link href="<?php echo $this->baseUrl('css/main.css');?>" media="screen" rel="Stylesheet" type="text/css" />
	</head>
	<body>
		<div id="page-wrap">
			<div id="header">
				<h1>Music</h1>
				<br /><br />
				<hr class="ns-divisor" />
			</div>
			<br />
			<div id="nav-container">
				<ul id="nav">
					<li><a href="">Dashboard</a></li>
				</ul>
			</div>
			<div id="content-container">
				<div id="content">
					<?php echo $this->layout()->content;?>
				</div>
				<div class="clear"></div>
			</div>
				
			<div id="footer">
				<hr class="ns-divisor" />
				<div class="copyright">&copy; &nbsp;&nbsp;All rights reserved.</div>
			</div>
		</div>
	</body>
</html>